DROP DATABASE IF EXISTS MMM;
CREATE DATABASE MMM;

USE MMM;
CREATE TABLE quotes(
    id INTEGER AUTO_INCREMENT,
    author VARCHAR(55) NOT NULL,
    quote VARCHAR(1000) NOT NULL,
    image VARCHAR(500) NOT NULL,
    PRIMARY KEY(id)
);