DROP DATABASE IF EXISTS MMM;
CREATE DATABASE MMM;
USE MMM;

CREATE TABLE `quotes` (
  `id` Int( 11 ) AUTO_INCREMENT NOT NULL,
  `author` VARCHAR( 255) NOT NULL,
  `quote` VARCHAR( 999 ) NOT NULL,
  `picture` VARCHAR(255) NOT NULL,
  PRIMARY KEY ( `id` ) 
);